import * as oidc from 'openid-client'
import {opaque,digest,equal,fault,cookieValue,sessionCookie,canonicalOrigin,localReturn} from './primitives.js'

export class FirstPartyClient {
 constructor({store,origin,issuer,clientId,tenantId,resolveAccount,test=false,fetcher=fetch}){this.store=store;this.origin=canonicalOrigin(origin,{test});this.issuer=canonicalOrigin(issuer,{test});this.clientId=clientId;this.tenantId=tenantId;this.resolveAccount=resolveAccount;this.test=test;this.fetcher=fetcher;this.cookieName='val_rp_'+clientId.replace(/-/g,'_');this.callback=origin+'/auth/oidc/callback'}
 async configuration(){if(!this.configPromise)this.configPromise=oidc.discovery(new URL(this.issuer),this.clientId,undefined,oidc.None(),{timeout:8,...(this.test?{execute:[oidc.allowInsecureRequests]}:{})}).then(c=>{const m=c.serverMetadata();for(const key of ['authorization_endpoint','token_endpoint','jwks_uri'])if(new URL(m[key]).origin!==this.issuer)throw fault('oidc_endpoint_origin_denied');return c}).catch(e=>{this.configPromise=null;throw e});return this.configPromise}
 async start({returnTo='/',contextRef=null,stepUp=false}={}){const config=await this.configuration(),verifier=oidc.randomPKCECodeVerifier(),challenge=await oidc.calculatePKCECodeChallenge(verifier),state=oidc.randomState(),nonce=oidc.randomNonce(),browserSecret=opaque();await this.store.put('rp-state',state,{tenantId:this.tenantId,verifier,nonce,browserHash:digest(browserSecret),returnTo:localReturn(returnTo),contextRef},300);const url=oidc.buildAuthorizationUrl(config,{redirect_uri:this.callback,response_type:'code',scope:'openid offline_access',code_challenge:challenge,code_challenge_method:'S256',state,nonce,acr_values:stepUp?'urn:val:aal2:recent':'urn:val:aal2',...(stepUp?{prompt:'login'}:{})});return {url:url.href,cookie:sessionCookie('val_oidc_state',browserSecret,{secure:!this.test,maxAge:300})}}
 async callbackRequest(req){const url=new URL(req.url,this.origin);const state=url.searchParams.get('state');const pending=state&&await this.store.take('rp-state',state);if(!pending||!equal(pending.browserHash,digest(cookieValue(req,'val_oidc_state'))))throw fault('oidc_state_invalid',401);const config=await this.configuration();const tokens=await oidc.authorizationCodeGrant(config,url,{pkceCodeVerifier:pending.verifier,expectedState:state,expectedNonce:pending.nonce,idTokenExpected:true});const claims=tokens.claims();if(!claims||claims.tenant_id!==this.tenantId||claims.auth_level!=='AAL2'||!claims.session_id||!claims.sub||!Number.isFinite(claims.mfa_authenticated_at))throw fault('oidc_identity_scope_denied');const account=await this.resolveAccount(claims);if(!account)throw fault('application_account_not_linked');const id=opaque();await this.store.put('rp-session',id,{tenantId:this.tenantId,userId:claims.sub,localId:account.id,centralSessionId:claims.session_id,tokens:{access_token:tokens.access_token,refresh_token:tokens.refresh_token},claims,accessExpiresAt:Date.now()+tokens.expires_in*1000,returnTo:pending.returnTo,contextRef:pending.contextRef},43200);return {cookie:sessionCookie(this.cookieName,id,{secure:!this.test}),clearState:sessionCookie('val_oidc_state','',{secure:!this.test,maxAge:0}),returnTo:pending.returnTo,contextRef:pending.contextRef}}
 async session(req){const id=cookieValue(req,this.cookieName);if(!id)return null;let v=await this.store.get('rp-session',id);if(!v)return null;try{if(v.accessExpiresAt<=Date.now()+10000)v=await this.store.update('rp-session',id,async current=>{if(current.accessExpiresAt>Date.now()+10000)return current;const tokens=await oidc.refreshTokenGrant(await this.configuration(),current.tokens.refresh_token);return {...current,tokens:{access_token:tokens.access_token,refresh_token:tokens.refresh_token},accessExpiresAt:Date.now()+tokens.expires_in*1000}});const r=await this.fetcher(this.issuer+'/identity/validate',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+v.tokens.access_token},body:JSON.stringify({client_id:this.clientId}),redirect:'error',signal:AbortSignal.timeout(8000)});const live=r.ok&&await r.json();if(!live?.active||live.aud!==this.clientId||live.iss!==this.issuer||live.tenant_id!==this.tenantId||live.sub!==v.userId||live.session_id!==v.centralSessionId||live.auth_level!=='AAL2')throw fault('central_session_inactive',401);const account=await this.resolveAccount(live);if(!account||account.id!==v.localId)throw fault('account_access_changed');return {...account,identity:{...live,localSessionId:digest(id)}}}catch{await this.store.remove('rp-session',id);return null}}
 async logout(req){const id=cookieValue(req,this.cookieName);if(id)await this.store.remove('rp-session',id);return sessionCookie(this.cookieName,'',{secure:!this.test,maxAge:0})}
}
